In [1]:
import os
import pandas as pd

from utils import clean_club, cat2sheet
from module_ranking import Ranking

grille = [100, 95, 90, 86, 82, 79, 76, 73, 70, 68, 66, 64, 62, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
          49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
grille += [0 for i in range(300)]

opt = {'ref_folder': 'results_challenge_2023'
}

categories = ['7/8 ans',
              '9/10 ans',
              '11/12 ans',
              '13/14 ans', 
              '15/16 ans', 
              'Scratch H', 'Scratch F', 
              '17/19 ans H', '17/29 ans F', 
              '20/29 ans H',
              '30/39 ans H', '30/39 ans F', 
              '40/49 ans H', '40 ans et + F', 
              '50/59 ans H',
              '60 ans et + H']
name = [cat2sheet(i) for i in categories]

In [12]:
ref_list = [os.path.join(opt['ref_folder'], i) for i in os.listdir(opt['ref_folder']) if i.endswith('.xlsx')]
references = {}
with pd.ExcelWriter('QG.xlsx') as writer: 
    for i,j in zip(name, categories):
        ranking = Ranking(grille)

        try:
            df = pd.read_excel(ref_list[0], sheet_name=i)
        except:
            df = pd.DataFrame(columns=['Classement', 'Nom affiché', 'Categorie', 'Sexe', 'Club', "1 - Ligne d'arrivée"])

        ranking.add_first_ranking(df)

        #print(ranking.rank)

        for k in range(1, len(ref_list)):
            try:
                df = pd.read_excel(ref_list[k], sheet_name=i)
            except:
                df = pd.DataFrame(columns=['Classement', 'Nom affiché', 'Categorie', 'Sexe', 'Club', "1 - Ligne d'arrivée"])

            ranking.add_ranking(df, k+1)

        ref = ranking.return_rank()
        ref['Display name'] = ref['Nom affiché'].apply(clean_club)
        references[j] = ref

        references[j].to_excel(writer, sheet_name=i)

/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']
/Users/claroche/Desktop/code_misegrille/module_ranking.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['Classement_1'] = self.rank['Classement'].apply(lambda x: rank2point(x, self.grille))
/Users/claroche/Desktop/code_misegrille/module_ranking.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.rank['tot'] = self.rank['Classement_1']

In [37]:
references['50/59 ans H']

,Classement,Nom affiché,Categorie,Sexe,Club,tot,Display name
0,1,Serge DAVESNE,50/59 ans H,HOMME,XC-Couronne,200,sergedavesne
1,2,Remi JOUANNIN,50/59 ans H,HOMME,xc couronne,190,remijouannin
2,3,Emmanuel CASTUS,50/59 ans H,HOMME,Requins Couronnais Triathlon,180,emmanuelcastus
3,4,Frédéric FLEURY,50/59 ans H,HOMME,XC Couronne,168,fredericfleury
4,5,Éric LE BOTMEL,50/59 ans H,HOMME,Rouen Triathlon,165,ericlebotmel
5,6,Herve LAROCHE,50/59 ans H,HOMME,Rouen Triathlon,152,hervelaroche
6,7,Thierry HAVE,50/59 ans H,HOMME,Cc tôtes 3 rivieres,152,thierryhave
7,8,Christophe BUCHY,50/59 ans H,HOMME,DEVILLE LES ROUEN,149,christophebuchy
8,9,Frederic LEFEBVRE,50/59 ans H,HOMME,UC Darnetal,138,fredericlefebvre
9,10,Mickael GUYOT,50/59 ans H,HOMME,Mtb racing,134,mickaelguyot
10,11,David GUILLAUME,50/59 ans H,HOMME,Vtt de la scie,121,davidguillaume
11,12,Jean Philippe FRANCOMME,50/59 ans H,HOMME,UV Louviers,121,jeanphilippefrancomme
12,13,Régis CHOPART,50/59 ans H,HOMME,Entente cycliste neufchateloise,120,regischopart
13,14,Nicolas BELLEST,50/59 ans H,HOMME,Rouen triathlon,112,nicolasbellest
14,15,Guy LECOMTE,50/59 ans H,HOMME,XC Couronne,76,guylecomte
15,16,David VALENTIN,50/59 ans H,HOMME,VTT Rouen,64,davidvalentin
16,17,Leconte LAURENT,50/59 ans H,HOMME,NaN,62,lecontelaurent
17,18,Sébastien ABRAHAM,50/59 ans H,HOMME,UC Envermeu,62,sebastienabraham
18,19,Martial PICARD,50/59 ans H,HOMME,As treport,59,martialpicard
19,20,Thierry VANENGELANDT,50/59 ans H,HOMME,NaN,58,thierryvanengelandt
20,21,Nicolas DIAGUILI,50/59 ans H,HOMME,VTT rouen,58,nicolasdiaguili
21,22,Rudy BECQUET,50/59 ans H,HOMME,glass vallée team bike,57,rudybecquet
22,23,Eric LANCIEN,50/59 ans H,HOMME,Accro Bike 76,56,ericlancien
23,24,Thierry COLOMBEL,50/59 ans H,HOMME,VC. Hautot,54,thierrycolombel
24,25,Johan FONTAINE,50/59 ans H,HOMME,AC SOTTEVILLE,52,johanfontaine

In [15]:
pd.read_excel(ref_list[0], sheet_name=i)

,Classement,Dossard,Nom affiché,Course,Categorie,Sexe,Club,Federation,1 - PP1,1 - Ligne d'arrivée,2 - PP1,2 - Ligne d'arrivée
0,1,601,Gauthier GODARD,7/8 ans,7/8 ans,HOMME,ucdarnetal,FFC,NaN,00:02:24,NaN,00:04:23
1,2,606,Timéo RIDEL,7/8 ans,7/8 ans,HOMME,ussapb,FFC,NaN,00:02:39,NaN,00:04:41
2,3,608,Matty BOUTARD,7/8 ans,7/8 ans,HOMME,astreportcyclisme,FSGT,NaN,00:02:43,NaN,00:04:44
3,4,611,Lelio BOYELDIEU,7/8 ans,7/8 ans,HOMME,vttdelascie,FSGT,NaN,00:02:47,NaN,00:04:46
4,5,602,Lucas PARENT,7/8 ans,7/8 ans,HOMME,ucdarnetal,FFC,NaN,00:02:42,NaN,00:04:51
5,6,612,Inès IKOUNA JOLY,7/8 ans,7/8 ans,FEMME,goevreuxgravigny,FFC,NaN,00:02:53,NaN,00:04:56
6,7,605,Nathis DENOMMEY,7/8 ans,7/8 ans,HOMME,NaN,NaN,NaN,00:02:50,NaN,00:05:00
7,8,604,Renan LANCHON BREUIL,7/8 ans,7/8 ans,HOMME,NaN,NaN,NaN,00:02:51,NaN,00:05:02
8,9,609,Tiago DE BASTOS,7/8 ans,7/8 ans,HOMME,vttdelascie,FSGT,NaN,00:03:02,NaN,00:05:04
9,10,613,Corentin HALBOURG,7/8 ans,7/8 ans,HOMME,longuevillesurscie,FSGT,NaN,00:02:57,NaN,00:05:08
10,11,603,Victor ANNE,7/8 ans,7/8 ans,HOMME,darnetal,FFC,NaN,00:02:55,NaN,00:05:16
11,12,610,Tom BOUL,7/8 ans,7/8 ans,HOMME,accrobike76,FSGT,NaN,00:02:59,NaN,00:05:18
12,13,614,Mathis VIAUD,7/8 ans,7/8 ans,HOMME,vc eudois,UFOLEP,NaN,00:03:13,NaN,00:05:46
13,14,607,Ewen MERIAU,7/8 ans,7/8 ans,HOMME,vcpacy,UFOLEP,NaN,NaN,NaN,NaN

In [11]:
pd.read_excel(ref_list[1], sheet_name=i)

/Users/claroche/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Rank,Bib Number,Display Name,Race Name,Category Name,Gender,Team,Federation,1 - PP1,1 - Ligne d'arrivée,2 - PP1,2 - Ligne d'arrivée
0,1,601,Gauthier GODARD,7/8 ans,7/8 ans,HOMME,UC darnetal,FFC,NaN,00:04:41,NaN,00:09:51
1,2,604,Lelio BOYELDIEU,7/8 ans,7/8 ans,HOMME,VTT DE LA SCIE,FSGT,NaN,00:05:35,NaN,00:11:11
2,3,605,Lucas PARENT,7/8 ans,7/8 ans,HOMME,UC Darnetal,FFC,NaN,00:05:43,NaN,00:11:13
3,4,618,Pacome SELLE,7/8 ans,7/8 ans,HOMME,msa triathlon,Autre Licence,NaN,00:05:50,NaN,00:11:33
4,5,602,Timéo RIDEL,7/8 ans,7/8 ans,HOMME,USSAPB,FFC,NaN,00:05:44,NaN,00:11:39
5,6,612,Ewen MERIAU,7/8 ans,7/8 ans,HOMME,VC PACY,UFOLEP,NaN,00:05:59,NaN,00:11:41
6,7,606,Inès IKOUNA JOLY,7/8 ans,7/8 ans,FEMME,GO Evreux Gravigny,FFC,NaN,00:05:51,NaN,00:11:53
7,8,603,Matty BOUTARD,7/8 ans,7/8 ans,HOMME,As treport cyclisme,FSGT,NaN,00:06:03,NaN,00:12:11
8,9,609,Tiago DE BASTOS,7/8 ans,7/8 ans,HOMME,Vtt de la scie,FSGT,NaN,00:06:19,NaN,00:12:17
9,10,617,Simon LOUËT,7/8 ans,7/8 ans,HOMME,HAC TRIATHLON,Autre Licence,NaN,00:06:14,NaN,00:12:17
10,11,611,Victor ANNE,7/8 ans,7/8 ans,HOMME,Darnetal,FFC,NaN,00:06:11,NaN,00:12:21
11,12,610,Corentin HALBOURG,7/8 ans,7/8 ans,HOMME,Vtt De la Scie,FSGT,NaN,00:06:33,NaN,00:12:38
12,13,616,Tom BOULANT,7/8 ans,7/8 ans,HOMME,Accro bike 76,FSGT,NaN,00:06:37,NaN,00:13:23
13,14,608,Renan LANCHON BREUIL,7/8 ans,7/8 ans,HOMME,NaN,NaN,NaN,00:07:12,NaN,00:13:58
14,15,615,Maël BELLET,7/8 ans,7/8 ans,HOMME,ECN,FSGT,NaN,00:07:14,NaN,00:14:19
15,16,607,Nathis DENOMMEY,7/8 ans,7/8 ans,HOMME,ACPA,Autre Licence,NaN,00:07:51,NaN,00:14:43
16,17,613,Mathys VIAUD,7/8 ans,7/8 ans,HOMME,Vc eudois et breslois,UFOLEP,NaN,00:07:53,NaN,00:15:10
17,18,614,Jerome LUCAS,7/8 ans,7/8 ans,HOMME,NaN,NaN,NaN,00:08:02,NaN,00:16:11

In [11]:
df = pd.read_excel('/Users/claroche/Desktop/code_misegrille/results_challenge_2023/res_manche2_2023.xlsx', sheet_name='Chrono - Scratch H')

In [13]:
df

,Classement,Dossard,Nom affiché,Course,Categorie,Sexe,Club,Federation,1 - PP1,1 - Ligne d'arrivée,2 - PP1,2 - Ligne d'arrivée,3 - PP1,3 - Ligne d'arrivée,4 - PP1,4 - Ligne d'arrivée,5 - PP1,5 - Ligne d'arrivée
0,1,1,Theo AUZOUX,Scratch H,20/29 ans H,HOMME,Cchartres,FFC,00:22:50,00:32:39,00:39:54,00:49:13,00:56:50,01:06:23,01:14:10,01:24:00,NaN,NaN
1,2,3,Damien GUILLEMET,Scratch H,30/39 ans H,HOMME,Xc couronne,FFC,00:22:51,00:32:41,00:40:07,00:49:58,00:57:35,01:07:22,01:14:58,01:24:59,NaN,NaN
2,3,4,Nathan DOUYERE,Scratch H,20/29 ans H,HOMME,Team jop 76,UFOLEP,00:23:22,00:33:22,00:41:08,00:51:06,00:58:54,01:08:57,01:16:47,01:26:53,NaN,NaN
3,4,33,Simon DECAYEUX,Scratch H,30/39 ans H,HOMME,NaN,NaN,00:24:16,00:33:53,00:41:40,00:51:41,00:59:32,01:09:36,01:17:17,01:27:17,NaN,NaN
4,5,32,Gabriel EUSTACHE,Scratch H,17/19 ans H,HOMME,UC DARNETAL,FFC,00:23:15,00:32:54,00:40:44,00:50:44,00:58:46,01:08:56,01:17:03,01:27:55,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,168,182,Baptiste OBE,Scratch H,30/39 ans H,HOMME,Accrobike76,FSGT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,169,34,Theo JOBBIN,Scratch H,20/29 ans H,HOMME,MSA triathlon,Autre Licence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,170,105,Jean Philippe FRANCOMME,Scratch H,50/59 ans H,HOMME,UV LOUVIERS,FFC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,171,101,Eric DORE,Scratch H,60 ans et + H,HOMME,ucve,UFOLEP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,172,107,Christophe LEVILLAIN,Scratch H,40/49 ans H,HOMME,VTT DE LA SCIE,FSGT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.dropna(subset=["1 - Ligne d'arrivée"])

,Classement,Dossard,Nom affiché,Course,Categorie,Sexe,Club,Federation,1 - PP1,1 - Ligne d'arrivée,2 - PP1,2 - Ligne d'arrivée,3 - PP1,3 - Ligne d'arrivée,4 - PP1,4 - Ligne d'arrivée,5 - PP1,5 - Ligne d'arrivée
0,1,1,Theo AUZOUX,Scratch H,20/29 ans H,HOMME,Cchartres,FFC,00:22:50,00:32:39,00:39:54,00:49:13,00:56:50,01:06:23,01:14:10,01:24:00,NaN,NaN
1,2,3,Damien GUILLEMET,Scratch H,30/39 ans H,HOMME,Xc couronne,FFC,00:22:51,00:32:41,00:40:07,00:49:58,00:57:35,01:07:22,01:14:58,01:24:59,NaN,NaN
2,3,4,Nathan DOUYERE,Scratch H,20/29 ans H,HOMME,Team jop 76,UFOLEP,00:23:22,00:33:22,00:41:08,00:51:06,00:58:54,01:08:57,01:16:47,01:26:53,NaN,NaN
3,4,33,Simon DECAYEUX,Scratch H,30/39 ans H,HOMME,NaN,NaN,00:24:16,00:33:53,00:41:40,00:51:41,00:59:32,01:09:36,01:17:17,01:27:17,NaN,NaN
4,5,32,Gabriel EUSTACHE,Scratch H,17/19 ans H,HOMME,UC DARNETAL,FFC,00:23:15,00:32:54,00:40:44,00:50:44,00:58:46,01:08:56,01:17:03,01:27:55,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,151,2,Nicolas RIHOUEY,Scratch H,20/29 ans H,HOMME,Uc darnetal,FFC,00:25:05,00:32:40,00:40:28,00:49:55,00:57:42,NaN,NaN,NaN,NaN,NaN
151,152,46,Axel LAFFONT,Scratch H,17/19 ans H,HOMME,Vc Val de reuil,FFC,00:26:58,00:39:39,00:50:26,01:08:17,NaN,NaN,NaN,NaN,NaN,NaN
152,153,74,Jérémy CARPENTIER,Scratch H,17/19 ans H,HOMME,Entente Cycliste Neufchâteloise,FSGT,00:33:31,00:47:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,154,55,Dorian DALBART,Scratch H,17/19 ans H,HOMME,NaN,NaN,00:35:08,00:50:42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,155,103,Dorian MOINET,Scratch H,20/29 ans H,HOMME,ACM,FFC,00:38:27,00:55:55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd

path = "data/results_challenge_2024/1ere-Manche-Challenge-Darnetalais-2024-export-2024-01-30.xlsx"
df = pd.read_excel(path, sheet_name=None)

/Users/claroche/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [19]:
cat_meg = ['Chrono - 78 ans',
        'Chrono - 1112 ans',
        'Chrono - 910 ans',
        'Chrono - 1314 ans',
        'Chrono - 1516 ans',
        'Chrono - Scratch H',
        'Chrono - Scratch F']

cat_gen = [ 'Chrono - 1719 ans H', 'Chrono - 1719 ans F',
            'Chrono - 2029 ans H', 'Chrono - 2029 ans F',
            'Chrono - 3039 ans H', 'Chrono - 3039 ans F',
            'Chrono - 4049 ans H', 'Chrono - 4049 ans F',
            'Chrono - 5059 ans H', 'Chrono - 50 ans et plus F',
            'Chrono - 60 ans et plus H',
            'Chrono - Tandem']

cat = cat_meg + cat_gen

In [22]:
grille = [100, 95, 90, 86, 82, 79, 76, 73, 70, 68, 66, 64, 62, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
          49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

grille += [1/i for i in range(2, 300)]

In [23]:
grille

[100,
 95,
 90,
 86,
 82,
 79,
 76,
 73,
 70,
 68,
 66,
 64,
 62,
 60,
 59,
 58,
 57,
 56,
 55,
 54,
 53,
 52,
 51,
 50,
 49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 4,
 3,
 2,
 1,
 0.5,
 0.3333333333333333,
 0.25,
 0.2,
 0.16666666666666666,
 0.14285714285714285,
 0.125,
 0.1111111111111111,
 0.1,
 0.09090909090909091,
 0.08333333333333333,
 0.07692307692307693,
 0.07142857142857142,
 0.06666666666666667,
 0.0625,
 0.058823529411764705,
 0.05555555555555555,
 0.05263157894736842,
 0.05,
 0.047619047619047616,
 0.045454545454545456,
 0.043478260869565216,
 0.041666666666666664,
 0.04,
 0.038461538461538464,
 0.037037037037037035,
 0.03571428571428571,
 0.034482758620689655,
 0.03333333333333333,
 0.03225806451612903,
 0.03125,
 0.030303030303030304,
 0.029411764705882353,
 0.02857142857142857,
 0.027777777777777776,
 0.02702702702702703,
 0.02631578947368421,
 0.02564102564102564,
 0.025,
 0.024390243902439025,
 0.023809523809523808,
 0.023255813953488372,
 0.022727272727272728,
 0.022222222222222223,
 0.021739130434782608,
 0.02127659574468085,
 0.020833333333333332,
 0.02040816326530612,
 0.02,
 0.0196078431372549,
 0.019230769230769232,
 0.018867924528301886,
 0.018518518518518517,
 0.01818181818181818,
 0.017857142857142856,
 0.017543859649122806,
 0.017241379310344827,
 0.01694915254237288,
 0.016666666666666666,
 0.01639344262295082,
 0.016129032258064516,
 0.015873015873015872,
 0.015625,
 0.015384615384615385,
 0.015151515151515152,
 0.014925373134328358,
 0.014705882352941176,
 0.014492753623188406,
 0.014285714285714285,
 0.014084507042253521,
 0.013888888888888888,
 0.0136986301369863,
 0.013513513513513514,
 0.013333333333333334,
 0.013157894736842105,
 0.012987012987012988,
 0.01282051282051282,
 0.012658227848101266,
 0.0125,
 0.012345679012345678,
 0.012195121951219513,
 0.012048192771084338,
 0.011904761904761904,
 0.011764705882352941,
 0.011627906976744186,
 0.011494252873563218,
 0.011363636363636364,
 0.011235955056179775,
 0.011111111111111112,
 0.01098901098901099,
 0.010869565217391304,
 0.010752688172043012,
 0.010638297872340425,
 0.010526315789473684,
 0.010416666666666666,
 0.010309278350515464,
 0.01020408163265306,
 0.010101010101010102,
 0.01,
 0.009900990099009901,
 0.00980392156862745,
 0.009708737864077669,
 0.009615384615384616,
 0.009523809523809525,
 0.009433962264150943,
 0.009345794392523364,
 0.009259259259259259,
 0.009174311926605505,
 0.00909090909090909,
 0.009009009009009009,
 0.008928571428571428,
 0.008849557522123894,
 0.008771929824561403,
 0.008695652173913044,
 0.008620689655172414,
 0.008547008547008548,
 0.00847457627118644,
 0.008403361344537815,
 0.008333333333333333,
 0.008264462809917356,
 0.00819672131147541,
 0.008130081300813009,
 0.008064516129032258,
 0.008,
 0.007936507936507936,
 0.007874015748031496,
 0.0078125,
 0.007751937984496124,
 0.007692307692307693,
 0.007633587786259542,
 0.007575757575757576,
 0.007518796992481203,
 0.007462686567164179,
 0.007407407407407408,
 0.007352941176470588,
 0.0072992700729927005,
 0.007246376811594203,
 0.007194244604316547,
 0.007142857142857143,
 0.0070921985815602835,
 0.007042253521126761,
 0.006993006993006993,
 0.006944444444444444,
 0.006896551724137931,
 0.00684931506849315,
 0.006802721088435374,
 0.006756756756756757,
 0.006711409395973154,
 0.006666666666666667,
 0.006622516556291391,
 0.006578947368421052,
 0.006535947712418301,
 0.006493506493506494,
 0.0064516129032258064,
 0.00641025641025641,
 0.006369426751592357,
 0.006329113924050633,
 0.006289308176100629,
 0.00625,
 0.006211180124223602,
 0.006172839506172839,
 0.006134969325153374,
 0.006097560975609756,
 0.006060606060606061,
 0.006024096385542169,
 0.005988023952095809,
 0.005952380952380952,
 0.005917159763313609,
 0.0058823529411764705,
 0.005847953216374269,
 0.005813953488372093,
 0.005780346820809248,
 0.005747126436781609,
 0.005714285714285714,
 0.005681818181818182,
 0.005649717514124294,
 0.0056179775280898875,
 0.00558659217877095,
 0.005555555555555556,
 0.0055248618784530384,
 0.005494505494505495,
 0.00546448087431694,
 0.005434782608695652,
 0.005405405405405406,
 0.005376344086021506,
 0.0053475935828877,
 0.005319148936170213,
 0.005291005291005291,
 0.005263157894736842,
 0.005235602094240838,
 0.005208333333333333,
 0.0051813471502590676,
 0.005154639175257732,
 0.005128205128205128,
 0.00510204081632653,
 0.005076142131979695,
 0.005050505050505051,
 0.005025125628140704,
 0.005,
 0.004975124378109453,
 0.0049504950495049506,
 0.0049261083743842365,
 0.004901960784313725,
 0.004878048780487805,
 0.0048543689320388345,
 0.004830917874396135,
 0.004807692307692308,
 0.004784688995215311,
 0.004761904761904762,
 0.004739336492890996,
 0.0047169811320754715,
 0.004694835680751174,
 0.004672897196261682,
 0.004651162790697674,
 0.004629629629629629,
 0.004608294930875576,
 0.0045871559633027525,
 0.0045662100456621,
 0.004545454545454545,
 0.004524886877828055,
 0.0045045045045045045,
 0.004484304932735426,
 0.004464285714285714,
 0.0044444444444444444,
 0.004424778761061947,
 0.004405286343612335,
 0.0043859649122807015,
 0.004366812227074236,
 0.004347826086956522,
 0.004329004329004329,
 0.004310344827586207,
 0.004291845493562232,
 0.004273504273504274,
 0.00425531914893617,
 0.00423728813559322,
 0.004219409282700422,
 0.004201680672268907,
 0.0041841004184100415,
 0.004166666666666667,
 0.004149377593360996,
 0.004132231404958678,
 0.00411522633744856,
 0.004098360655737705,
 0.004081632653061225,
 0.0040650406504065045,
 0.004048582995951417,
 0.004032258064516129,
 0.004016064257028112,
 0.004,
 0.00398406374501992,
 0.003968253968253968,
 0.003952569169960474,
 0.003937007874015748,
 0.00392156862745098,
 0.00390625,
 0.0038910505836575876,
 0.003875968992248062,
 0.003861003861003861,
 0.0038461538461538464,
 0.0038314176245210726,
 0.003816793893129771,
 0.0038022813688212928,
 0.003787878787878788,
 0.0037735849056603774,
 0.0037593984962406013,
 0.003745318352059925,
 0.0037313432835820895,
 0.0037174721189591076,
 0.003703703703703704,
 0.0036900369003690036,
 0.003676470588235294,
 0.003663003663003663,
 0.0036496350364963502,
 0.0036363636363636364,
 0.0036231884057971015,
 0.0036101083032490976,
 0.0035971223021582736,
 0.0035842293906810036,
 0.0035714285714285713,
 0.0035587188612099642,
 0.0035460992907801418,
 0.0035335689045936395,
 0.0035211267605633804,
 0.0035087719298245615,
 0.0034965034965034965,
 0.003484320557491289,
 0.003472222222222222,
 0.0034602076124567475,
 0.0034482758620689655,
 0.003436426116838488,
 0.003424657534246575,
 0.0034129692832764505,
 0.003401360544217687,
 0.003389830508474576,
 0.0033783783783783786,
 0.003367003367003367,
 0.003355704697986577,
 0.0033444816053511705]